services:

  client:
    build:
      context: ./client/
    ports:
      - 5500:80

  server:
    build:
      context: ./server/
    ports:
      - 8080:8080
    network_mode: 'host'

  redis:
    build:
      context: ./redis/
    ports:
      - 6379:6379